### ISSUE TITLE
ModuleNotFoundError: No module named 'clipperpy.clipperpy'

### ISSUE THREAD

**Issue by TheCuriousJoe** [HKUST-Aerial-Robotics/MonoLaneMapping#2]
When i run "python examples/demo_mapping.py --cfg_file=config/lane_mapping.yaml", I get the following issue:
> python examples/demo_mapping.py --cfg_file=config/lane_mapping.yaml
Traceback (most recent call last):
  File "examples/demo_mapping.py", line 14, in <module>
    from lane_slam.system.lane_mapping import LaneMapping
  File "/home/w/catkin_ws/src/MonoLaneMapping/lane_slam/system/lane_mapping.py", line 9, in <module>
    from lane_slam.system.lane_opt import LaneOptimizer
  File "/home/w/catkin_ws/src/MonoLaneMapping/lane_slam/system/lane_opt.py", line 19, in <module>
    from lane_slam.system.lane_tracker import LaneTracker
  File "/home/w/catkin_ws/src/MonoLaneMapping/lane_slam/system/lane_tracker.py", line 9, in <module>
    from lane_slam.system.lane_ui import LaneUI
  File "/home/w/catkin_ws/src/MonoLaneMapping/lane_slam/system/lane_ui.py", line 14, in <module>
    from lane_slam.assoc_utils import draw_correspondences, draw_lines
  File "/home/w/catkin_ws/src/MonoLaneMapping/lane_slam/assoc_utils.py", line 6, in <module>
    import clipperpy
  File "/home/w/Software/anaconda3/envs/lanemapping/lib/python3.8/site-packages/clipperpy/__init__.py", line 1, in <module>
    from .clipperpy import *
ModuleNotFoundError: No module named 'clipperpy.clipperpy'

I have followed the [modified version](https://github.com/qiaozhijian/clipper.git) to install CLIPPER with Python Bindings.

how I can fix this problem? thx a lot!

**Comment by qiaozhijian** [comment]
I have deleted clipper since it's not the method we choose in the final system. Please try to update this repo. If it's solved, could you close this issue? Thanks!

**Comment by TheCuriousJoe** [comment]
Since you have removed the clipperpy module, there is no import error for the module. I have closed the issue, thanks!

**Comment by TheCuriousJoe** [comment]
Since you have removed the clipperpy module, there is no import error for the module. I have closed the issue, thanks!
