### ISSUE TITLE
AttributeError: module 'gtsam' has no attribute 'CustomFactor'

### ISSUE THREAD

**Issue by BUAA-RickyLi** [HKUST-Aerial-Robotics/MonoLaneMapping#5]
Hi, Thank you for your excellent work! A question have happened when i tried to run "python examples/demo_mapping.py --cfg_file=config/lane_mapping.yaml". More details like follows:

```
Traceback (most recent call last):
  File "examples/demo_mapping.py", line 14, in <module>
    from lane_slam.system.lane_mapping import LaneMapping
  File "xxx/monolane/MonoLaneMapping/lane_slam/system/lane_mapping.py", line 9, in <module>
    from lane_slam.system.lane_opt import LaneOptimizer
  File "xxx/monolane/MonoLaneMapping/lane_slam/system/lane_opt.py", line 17, in <module>
    from lane_slam.factors import error_catmull_rom, p2tan_catmull_rom, chord_factor, p2tan_factor, \
  File "xxx/monolane/MonoLaneMapping/lane_slam/factors.py", line 7, in <module>
    def error_catmull_rom(measurement: np.ndarray, this: gtsam.CustomFactor,
AttributeError: module 'gtsam' has no attribute 'CustomFactor'
```

When I treid to solve the problem, I noticed when i used "print(help(gtsam.gtsam))", it worked. When i used "help(gtsam.CustomFactor)", the output as follows:

```
>>> print(help(gtsam.CustomFactor))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gtsam' has no attribute 'CustomFactor
```

Could you please tell me how to solve this problem? Thanks!

**Comment by Guo-hk** [comment]
It could be that your GTSAM version is not compatible. You can try the latest tag on GitHub.

**Comment by BUAA-RickyLi** [comment]
> It could be that your GTSAM version is not compatible. You can try the latest tag on GitHub.

Hi, Thank you for your reply, I used "develop" branch, which is called "Pre 4.3" version. Could you please tell me which version/tag could work? Thanks a lot!

**Comment by BUAA-RickyLi** [comment]
> 
Hi Thank you for you suggestion, it works after I change GTSAM version into branch 4.1.

**Comment by BUAA-RickyLi** [comment]
Another error occured, when I tried to run "python examples/demo_mapping.py --cfg_file=config/lane_mapping.yaml", More details like follows:
```
INFO - 2023-08-17 14:48:30,433 - _logger - Log opened: Thu Aug 17 06:48:30 2023 UTC
INFO - 2023-08-17 14:48:30,446 - topics - topicmanager initialized
Load config file:  config/lane_mapping.yaml
Traceback (most recent call last):
  File "examples/demo_mapping.py", line 65, in <module>
    main(bag_file)
  File "examples/demo_mapping.py", line 23, in main
    lane_mapper = LaneMapping(bag_file)
  File "xxx/monolane/src/MonoLaneMapping/lane_slam/system/lane_mapping.py", line 19, in __init__
    self.graph_init()
  File "xxx/monolane/src/MonoLaneMapping/lane_slam/system/lane_opt.py", line 492, in graph_init
    parameters.relinearizeSkip = 0 # default 10
AttributeError: 'gtsam.gtsam.ISAM2Params' object has no attribute 'relinearizeSkip'
INFO - 2023-08-17 14:48:32,475 - core - signal_shutdown [atexit]
```

**Comment by BUAA-RickyLi** [comment]
> 

After change "xxx/monolane/src/MonoLaneMapping/lane_slam/system/lane_opt.py", line 492 & 493 to:
```
            parameters.setRelinearizeSkip(0) # default 10
            parameters.setEnableRelinearization(False) # default true
```
it works.
