### ISSUE TITLE
GTSAM version

### ISSUE THREAD

**Issue by BUAA-RickyLi** [HKUST-Aerial-Robotics/MonoLaneMapping#6]
Hi, Thank you for your excellent work again! When I tried to run "python examples/demo_curve_fitting.py", some error happened. More details as follows:
```
Load config file:  config/lane_mapping.yaml
Traceback (most recent call last):                                                                                
  File "examples/demo_mapping.py", line 65, in <module>
    main(bag_file)
  File "examples/demo_mapping.py", line 25, in main
    stats = lane_mapper.process()
  File "/catkin_ws/src/MonoLaneMapping/lane_slam/system/lane_mapping.py", line 41, in process
    self.map_update()
  File "/catkin_ws/src/MonoLaneMapping/lane_slam/system/lane_opt.py", line 32, in map_update
    self.build_graph()
  File "/catkin_ws/src/MonoLaneMapping/lane_slam/system/lane_opt.py", line 128, in build_graph
    self.initial_estimate.insert_or_assign(key, gtsam.Point3(ctrl_pt.item))
AttributeError: 'gtsam.gtsam.Values' object has no attribute 'insert_or_assign'
```
I have read some doc about GTSAM, some version have 'insert_or_assign' such as https://gtsam-jlblanco-docs.readthedocs.io/en/latest/_static/doxygen/html/classgtsam_1_1Values.html, but some not such as https://gtsam.org/doxygen/4.0.0/a03871.html.
So could you tell me your GTSAM version so that I could reproduce your great result? Thanks!
I am using "https://github.com/borglab/gtsam" branch called "4.1", which is 4.1.1 version

**Comment by qiaozhijian** [comment]
Thank you for the interest. My GTSAM config.h is as follows,
```
// Library version
#define GTSAM_VERSION_MAJOR 4
#define GTSAM_VERSION_MINOR 2
#define GTSAM_VERSION_PATCH 0
#define GTSAM_VERSION_NUMERIC 40200
#define GTSAM_VERSION_STRING "4.2a8"
```
